/* ────────────────────────────────────────────────────────────────
  8.  Static data & helpers
──────────────────────────────────────────────────────────────── */
const bankOptions = [
  { value: '790', label: 'ABU DHABI SECURITIES EXCHANGE' },
  { value: '118', label: 'AMEX (Middle East) - B.S.C' },
  { value: '083', label: 'Aafaq Islamic Finance PSC' },
  { value: '003', label: 'Abu Dhabi Commercial Bank' },
  { value: '050', label: 'Abu Dhabi Islamic Bank' },
  { value: '856', label: 'Abu Dhabi Retirement Pension Benefit Fund' },
  { value: '057', label: 'Ajman Bank' },
  { value: '004', label: 'Al Ahli Bank Of Kuwait K.S.C.' },
  { value: '120', label: 'Al Ain Finance PJSC' },
  { value: '206', label: 'Al Ansari Exchange' },
  { value: '215', label: 'Al Fardan Exchange' },
  { value: '110', label: 'Al Hail Orix' },
  { value: '053', label: 'Al Hilal Bank' },
  { value: '017', label: 'Al Khaliji France S.A.' },
  { value: '097', label: 'Al Maryah Community Bank' },
  { value: '008', label: 'Al Masraf' },
  { value: '007', label: 'Arab African International Bank' },
  { value: '009', label: 'Arab Bank' },
  { value: '048', label: 'Arab Emirates Investment Bank' },
  { value: '015', label: 'BANQUE MISR' },
  { value: '018', label: 'BNP Paribas' },
  { value: '094', label: 'BOK International Bank' },
  { value: '011', label: 'Bank of Baroda' },
  { value: '012', label: 'Bank of Sharjah' },
  { value: '014', label: 'Banque Banorient France' },
  { value: '019', label: 'Barclays Bank' },
  { value: '892', label: 'CBUAE - IA Charges' },
  { value: '016', label: 'Calyon Investment and Corporate Bank' },
  { value: '992', label: 'Central bank of the UAE - Staff Loan' },
  { value: '021', label: 'Citibank NA' },
  { value: '022', label: 'Commercial Bank International PSC' },
  { value: '023', label: 'Commercial Bank of Dubai' },
  { value: '919', label: 'DDS Market Place(DDMP)  NBF' },
  { value: '082', label: 'DEEM FINANCE' },
  { value: '049', label: 'Deutsche Bank' },
  { value: '054', label: 'Doha Bank' },
  { value: '051', label: 'Dubai Bank' },
  { value: '100', label: 'Dubai First PJSC' },
  { value: '024', label: 'Dubai Islamic Bank' },
  { value: '958', label: 'Dubai Police - DDS' },
  { value: '025', label: 'El Nilein Bank' },
  { value: '809', label: 'Emirates Development Bank' },
  { value: '034', label: 'Emirates Islamic Bank PJSC' },
  { value: '026', label: 'Emiratesnbd Bank PJSC' },
  { value: '890', label: 'Etisalat (eand)' },
  { value: '081', label: 'Finance House' },
  { value: '035', label: 'First Abu Dhabi Bank' },
  { value: '027', label: 'First Abu Dhabi Bank-Erstwhile FGB' },
  { value: '854', label: 'GPSSA - DDS' },
  { value: '020', label: 'HSBC Middle East' },
  { value: '029', label: 'Habib Bank AG Zurich' },
  { value: '028', label: 'Habib Bank Limited' },
  { value: '043', label: 'Industrial and Commercial Bank of China' },
  { value: '030', label: 'Investbank PSC' },
  { value: '088', label: 'Islamic Finance House' },
  { value: '031', label: 'Janata Bank' },
  { value: '836', label: 'Khalifa Fund' },
  { value: '089', label: 'Korea Exchange Bank(Bank ID-089)' },
  { value: '085', label: 'MAF Finance' },
  { value: '033', label: 'Mashreqbank PSC' },
  { value: '084', label: 'Mawarid Finance' },
  { value: '036', label: 'National Bank Of Bahrain' },
  { value: '038', label: 'National Bank Of Fujairah' },
  { value: '056', label: 'National Bank Of Kuwait' },
  { value: '042', label: 'National Bank Of Umm Al Qaiwain' },
  { value: '039', label: 'National Bank of Oman' },
  { value: '150', label: 'National Bonds Corporation PJSC' },
  { value: '052', label: 'Noor Islamic Bank' },
  { value: '040', label: 'RAK Bank' },
  { value: '005', label: 'Rafidain Bank' },
  { value: '101', label: 'Reem Finance PJSC' },
  { value: '132', label: 'Ruya community Islamic Bank' },
  { value: '055', label: 'SAMBA Financial Group' },
  { value: '041', label: 'Sharjah Islamic Bank' },
  { value: '113', label: 'Siraj Finance' },
  { value: '044', label: 'Standard Chartered Bank' },
  { value: 'XX2', label: 'The Royal Bank Of Scotland PLC' },
  { value: '045', label: 'Union National Bank' },
  { value: '046', label: 'United Arab Bank' },
  { value: '047', label: 'United Bank Ltd.' },
  { value: '086', label: 'Wio Bank PJSC' },
]
export default bankOptions
